### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by mond-cz** [martijnberger/pyslapi#1]
Does it supposed to work under OS X too? 
Some time ago I downloaded folder "sketchup importer" into add ons folder, 
![screen shot 2015-02-01 at 17 00 00](https://cloud.githubusercontent.com/assets/649050/5992705/5294b99a-aa34-11e4-86cc-491388f348f1.png)
but I wasn't able to even find in blender's addon list to enable it.

Today your "sketchup importer" folder consists only from "_init_.py" file.

I can't remember where from I came a cross to your work. Can you direct me for more informations how to use it? Or does it in a testing stage? Thank you for answer.

**Comment by martijnberger** [comment]
you should be able to select the zip in blender's addons dialog and install it from there.
