### ISSUE TITLE
Update to Blender 2.79b

### ISSUE THREAD

**Issue by nigec** [martijnberger/pyslapi#28]
Blender complains the python version is incorrect so the addon doesn't work
`\2.79\scripts\addons\sketchup_importer\__init__.py", line 32, in <module>
    from . import sketchup
ImportError: Module use of python34.dll conflicts with this version of Python.`

**Comment by Jangalang** [comment]
Same version... Blender does nothing. Click to open, and Blender tries nothing.

**Comment by melMass** [comment]
Yes @martijnberger can you rebuild the addon using Python 3.7 ? It requires an application to the SketchupSDK which I'm still waiting for approval.

**Comment by melMass** [comment]
Received the approval, here is the **OSX Blender 2.79b (Python 3.7)** compiled version:
[sketchup_importer_2_79b_python37_osx.zip](https://github.com/martijnberger/pyslapi/files/2615895/sketchup_importer_2_79b_python37_osx.zip)

**Comment by alperomeresin** [comment]
A few months ago I've installed skp importer addon to 2.79b. It was working by stroke of luck. Now after format my pc addon is not working. Not working on 2.80 too. Mr Martin not updating or answering nobody. We need import skp files to blender soon.

**Comment by martijnberger** [comment]
https://github.com/martijnberger/pyslapi/releases/tag/0.20
