### ISSUE TITLE
Can´t install the ADDON

### ISSUE THREAD

**Issue by TheLooking** [martijnberger/pyslapi#33]
I see the addon in the prefrences, but i can´t enable it...?

**Comment by dannysetvisions** [comment]
same here. 2.81
any news on this?

**Comment by ThoMiCroN** [comment]
Even when you change the __init__.py file, it won't be enabled.

**Comment by martijnberger** [comment]
This is a known issue. The current released versions i only compatible with 2.79

**Comment by martijnberger** [comment]
This is a duplicate of 
Duplicate of #31
