### ISSUE TITLE
UVs are still wrong sometime

### ISSUE THREAD

**Issue by mirlip** [martijnberger/pyslapi#4]
Sometime, the textures displayed are heavily distorted. Another user here:http://blenderartists.org/forum/showthread.php?360406-Sketchup-(SKP)-importer&s=0c14edf77210e596dffb613aba6eaef5&p=2895568&viewfull=1#post2895568 confirmed the issue with a scene from 3D warehouse ( https://3dwarehouse.sketchup.com/model.html?id=2376534180d03ff22d8947b1dd299e81 )

**Comment by martijnberger** [comment]
Should be fixed now.

**Comment by mirlip** [comment]
just tested with latest .pyd and __init__.py and it still has the bug. Do we need a new binary for this https://dl.dropboxusercontent.com/u/10491635/sketchup_importer.zip ?

**Comment by martijnberger** [comment]
https://github.com/martijnberger/pyslapi/releases/download/0.11/sketchup_importer_0.1.1.zip 

the release as published on github

**Comment by martijnberger** [comment]
the bug was sketchup doing some STQ coords and I was only using ST components. 
I think you are using the wrong .pyd.. as the that contains the actual fix

**Comment by mirlip** [comment]
yes, sorry it works. I used the files from source, not the zip. Nice job, thanks a lot :)
