### ISSUE TITLE
possible Blender render option?

### ISSUE THREAD

**Issue by andrewfrueh** [martijnberger/pyslapi#7]
This is not really an "issue" but more of a request (sorry if this is the wrong place to do this).

First off, thank you thank you thank you!!! Your plugin is awesome and has allowed me to use models from the Sketchup warehouse which is huge!

I am currently working on a VR project called Historical Explorer -- you can see it on my site here:
http://www.andrewfrueh.com/portfolio/historical-explorer-domus/

I am importing the Sketchup file into Blender (with your plugin) and then importing from Blender to Unity. The problem is that Unity only parses materials and textures properly from Blender render mode (not Cycles). This means I have tons of work re-assigning the textures to the materials once I get into Unity.

My request: I would love it the plugin had an option (even if it had to be set manually in the code) that would let me run it in Blender render mode (not only in Cycles). I looked over the code, and I understand where the changes need to be made (around lines 250-300), but alas, every time I try to make changes, I only end up crashing the plugin. 

I would be happy to help, but I don't really understand how to transition from using "bpy" to the standard "Image" and "Material" calls. I think I am out of my depth, and I'm hoping that you can assist me or add this feature as it would really help me with this kind of work.

**Comment by lalamax3d** [comment]
ahh, similar request from my side , after saying thanks for awesomeness.
