### ISSUE TITLE
always the same bugs

### ISSUE THREAD

**Issue by jolhirsute** [martijnberger/pyslapi#8]
Hello thanks to you first.

I have most of time this message on import :

>location: \<unknown location\>:-1

>KeyError: 'bpy_prop_collection[key]: key "Diffuse BSDF" not found'
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 298, in write_materials
    bmat.node_tree.links.new(n.outputs['Color'], bmat.node_tree.nodes['Diffuse BSDF'].inputs['Color'] )
    self.write_materials(self.skp_model.materials)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 157, in load
    return SceneImporter().set_filename(keywords['filepath']).load(context, **keywords)
  File "C:\Users\seb\AppData\Roaming\Blender Foundation\Blender\2.75\scripts\addons\sketchup_importer\__init__.py", line 645, in execute
Traceback (most recent call last):

Any idea ?

**Comment by martijnberger** [comment]
Could you give me one of the files that break for you ?

**Comment by jolhirsute** [comment]
I try several files with and without Scenes & Camera and I have only camera but no object in most of them.

"Sapin dans la neige" works
[sapin dans la neige.zip](https://github.com/martijnberger/pyslapi/files/80297/sapin.dans.la.neige.zip)

This one, for exemple, not
[anarchie game 4 box.zip](https://github.com/martijnberger/pyslapi/files/80302/anarchie.game.4.box.zip)

**Comment by jolhirsute** [comment]
Hello, 
have you some news ?
I can make tests if you want.

**Comment by martijnberger** [comment]
https://www.dropbox.com/s/2tmq5srcmzt0k3c/sketchup_importer_py3.4_winx64.zip?dl=0

**Comment by jolhirsute** [comment]
Exactly the same, I'm afraid. The same files works, the other not like before.
