### ISSUE TITLE
No SketchUp 2016 Support

### ISSUE THREAD

**Issue by forby** [martijnberger/pyslapi#9]
No results of any kind (error or otherwise) when trying to import a .skp file from SketchUp 2016 (v16+).

**Comment by martijnberger** [comment]
I will update and add sketchup 2016 support

**Comment by forby** [comment]
Thanks!  Seriously great work.  Saved me so much time :)

**Comment by martijnberger** [comment]
https://www.dropbox.com/s/2tmq5srcmzt0k3c/sketchup_importer_py3.4_winx64.zip?dl=0

**Comment by forby** [comment]
Maybe we can get someone else to test this, I'm on a Mac :sweat_smile:

**Comment by forby** [comment]
I think this has been fixed :) thanks!
